run:
	java -cp .:mysql-connector.jar Main

build:
	javac Main.java DatabaseAccess.java Accesses.java Audio.java Book.java \
		Checkout.java Customer.java Employee.java Item.java Library.java \
		Loan.java Movie.java

